---
title: "COVID-19 Data Science Project"
author: "Learner"
date: "2023-01-31"
output:
  word_document: default
  html_document: default
---


# PLEASE RUN THE CODES BELOW, EACH STEP PRESENTED IN THE COURSE IS PERFORMED BELOW(IT IS REPREDUCABLE CODE) "Thank You"


# Step 1: Importing the Data: the Question is : "Start an Rmd document that describes and imports the shooting project dataset in a reproducible manner."

library(tidyverse)



```
\section(table)
── Attaching packages ──────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0      ✔ purrr   1.0.1 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.3.0      ✔ stringr 1.5.0 
✔ readr   2.1.3      ✔ forcats 0.5.2 
── Conflicts ─────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
```

library(tinytex)
library(lubridate)



```
\section(table)
Attaching package: ‘lubridate’

The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union
```


url_in <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/"


file_names <- c("time_series_covid19_confirmed_global.csv", "time_series_covid19_deaths_global.csv", "time_series_covid19_confirmed_US.csv", "time_series_covid19_deaths_US.csv")



urls <- str_c(url_in, file_names)


urls

```
\section(table)
[1] "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
[2] "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"   
[3] "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv"    
[4] "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv" 
```


global_cases = read_csv(urls[1])


```
section(table)

Rows: 289 Columns: 1109                                        
── Column specification ─────────────────────────────────────────
Delimiter: ","
chr    (2): Province/State, Country/Region
dbl (1107): Lat, Long, 1/22/20, 1/23/20, 1/24/20, 1/25/20, 1/...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
```

global_deaths = read_csv(urls[2])


```
\section(table)
chr    (2): Province/State, Country/Region
dbl (1107): Lat, Long, 1/22/20, 1/23/20, 1/24/20, 1/25/20, 1/...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
```


US_cases = read_csv(urls[3])



```
\section(table)
Rows: 3342 Columns: 1116                                       
── Column specification ─────────────────────────────────────────
Delimiter: ","
chr    (6): iso2, iso3, Admin2, Province_State, Country_Regio...
dbl (1110): UID, code3, FIPS, Lat, Long_, 1/22/20, 1/23/20, 1...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
```


US_deaths <- read_csv(urls[4])


```
\section(table)

chr    (6): iso2, iso3, Admin2, Province_State, Country_Regio...
dbl (1111): UID, code3, FIPS, Lat, Long_, Population, 1/22/20...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
```

# Step 2: Tidy & Transform the Data, the question is : "Add to your Rmd document a summary of the data and clean up your dataset by changing appropriate variables to factor and date types and getting rid of any columns not needed.  Show the summary of your data to be sure there is no missing data. If there is missing data, describe how you plan to handle it."

global_cases <- global_cases %>% pivot_longer(cols = -c('Province/State', 'Country/Region', Lat, Long), names_to = "date", values_to = "cases") %>% select(-c(Lat, Long))



global_cases


```
\section(table)
# A tibble: 319,345 × 4
   `Province/State` `Country/Region` date    cases
   <chr>            <chr>            <chr>   <dbl>
 1 NA               Afghanistan      1/22/20     0
 2 NA               Afghanistan      1/23/20     0
 3 NA               Afghanistan      1/24/20     0
 4 NA               Afghanistan      1/25/20     0
 5 NA               Afghanistan      1/26/20     0
 6 NA               Afghanistan      1/27/20     0
 7 NA               Afghanistan      1/28/20     0
 8 NA               Afghanistan      1/29/20     0
 9 NA               Afghanistan      1/30/20     0
10 NA               Afghanistan      1/31/20     0
# … with 319,335 more rows
# ℹ Use `print(n = ...)` to see more rows
```

global_deaths <- global_deaths %>% pivot_longer(cols = -c("Province/State", "Country/Region", Lat, Long), names_to = "date", values_to = "deaths") %>% select(-c(Lat, Long))

global_deaths



```
\section(table)
# A tibble: 319,345 × 4
   `Province/State` `Country/Region` date    deaths
   <chr>            <chr>            <chr>    <dbl>
 1 NA               Afghanistan      1/22/20      0
 2 NA               Afghanistan      1/23/20      0
 3 NA               Afghanistan      1/24/20      0
 4 NA               Afghanistan      1/25/20      0
 5 NA               Afghanistan      1/26/20      0
 6 NA               Afghanistan      1/27/20      0
 7 NA               Afghanistan      1/28/20      0
 8 NA               Afghanistan      1/29/20      0
 9 NA               Afghanistan      1/30/20      0
10 NA               Afghanistan      1/31/20      0
# … with 319,335 more rows
# ℹ Use `print(n = ...)` to see more rows
```


global <- global_cases %>% full_join(global_deaths) %>% rename(Country_Region = "Country/Region", Province_State = "Province/State") %>% mutate(date = mdy(date))



```
\section(table)
Joining, by = c("Province/State", "Country/Region", "date")
```

global



```
\section(table)
# A tibble: 319,345 × 5
   Province_State Country_Region date       cases deaths
   <chr>          <chr>          <date>     <dbl>  <dbl>
 1 NA             Afghanistan    2020-01-22     0      0
 2 NA             Afghanistan    2020-01-23     0      0
 3 NA             Afghanistan    2020-01-24     0      0
 4 NA             Afghanistan    2020-01-25     0      0
 5 NA             Afghanistan    2020-01-26     0      0
 6 NA             Afghanistan    2020-01-27     0      0
 7 NA             Afghanistan    2020-01-28     0      0
 8 NA             Afghanistan    2020-01-29     0      0
 9 NA             Afghanistan    2020-01-30     0      0
10 NA             Afghanistan    2020-01-31     0      0
# … with 319,335 more rows
# ℹ Use `print(n = ...)` to see more rows
```


summary(global)



```
\section(table)
 Province_State     Country_Region          date           
 Length:319345      Length:319345      Min.   :2020-01-22  
 Class :character   Class :character   1st Qu.:2020-10-24  
 Mode  :character   Mode  :character   Median :2021-07-27  
                                       Mean   :2021-07-27  
                                       3rd Qu.:2022-04-29  
                                       Max.   :2023-01-30  
     cases               deaths       
 Min.   :        0   Min.   :      0  
 1st Qu.:      603   1st Qu.:      3  
 Median :    13122   Median :    139  
 Mean   :   912205   Mean   :  13024  
 3rd Qu.:   214636   3rd Qu.:   2897  
 Max.   :102310636   Max.   :1107855
 ```
 
 
 global <- global %>% filter(cases > 0)
 
 
summary(global)




```
\section(table)
 Province_State     Country_Region          date           
 Length:295921      Length:295921      Min.   :2020-01-22  
 Class :character   Class :character   1st Qu.:2020-12-02  
 Mode  :character   Mode  :character   Median :2021-08-27  
                                       Mean   :2021-08-23  
                                       3rd Qu.:2022-05-17  
                                       Max.   :2023-01-30  
     cases               deaths       
 Min.   :        1   Min.   :      0  
 1st Qu.:     1202   1st Qu.:      7  
 Median :    18797   Median :    199  
 Mean   :   984412   Mean   :  14055  
 3rd Qu.:   258540   3rd Qu.:   3547  
 Max.   :102310636   Max.   :1107855  
 ```
 
global %>% filter(cases > 28000000)



```
\section(table)
# A tibble: 2,244 × 5
   Province_State Country_Region date          cases deaths
   <chr>          <chr>          <date>        <dbl>  <dbl>
 1 NA             Brazil         2022-02-18 28072238 643340
 2 NA             Brazil         2022-02-19 28177367 644195
 3 NA             Brazil         2022-02-20 28218180 644592
 4 NA             Brazil         2022-02-21 28258458 644918
 5 NA             Brazil         2022-02-22 28361951 645735
 6 NA             Brazil         2022-02-23 28493336 646714
 7 NA             Brazil         2022-02-24 28589235 647703
 8 NA             Brazil         2022-02-25 28679671 648496
 9 NA             Brazil         2022-02-26 28749552 649184
10 NA             Brazil         2022-02-27 28776794 649437
# … with 2,234 more rows
# ℹ Use `print(n = ...)` to see more rows
```

##### lets wprk on US cases: 

US_cases


```
\section(table)
# A tibble: 3,342 × 1,116
        UID iso2  iso3  code3  FIPS Admin2 Provi…¹ Count…²   Lat Long_
      <dbl> <chr> <chr> <dbl> <dbl> <chr>  <chr>   <chr>   <dbl> <dbl>
 1 84001001 US    USA     840  1001 Autau… Alabama US       32.5 -86.6
 2 84001003 US    USA     840  1003 Baldw… Alabama US       30.7 -87.7
 3 84001005 US    USA     840  1005 Barbo… Alabama US       31.9 -85.4
 4 84001007 US    USA     840  1007 Bibb   Alabama US       33.0 -87.1
 5 84001009 US    USA     840  1009 Blount Alabama US       34.0 -86.6
 6 84001011 US    USA     840  1011 Bullo… Alabama US       32.1 -85.7
 7 84001013 US    USA     840  1013 Butler Alabama US       31.8 -86.7
 8 84001015 US    USA     840  1015 Calho… Alabama US       33.8 -85.8
 9 84001017 US    USA     840  1017 Chamb… Alabama US       32.9 -85.4
10 84001019 US    USA     840  1019 Chero… Alabama US       34.2 -85.6
# … with 3,332 more rows, 1,106 more variables: Combined_Key <chr>,
#   `1/22/20` <dbl>, `1/23/20` <dbl>, `1/24/20` <dbl>,
#   `1/25/20` <dbl>, `1/26/20` <dbl>, `1/27/20` <dbl>,
#   `1/28/20` <dbl>, `1/29/20` <dbl>, `1/30/20` <dbl>,
#   `1/31/20` <dbl>, `2/1/20` <dbl>, `2/2/20` <dbl>, `2/3/20` <dbl>,
#   `2/4/20` <dbl>, `2/5/20` <dbl>, `2/6/20` <dbl>, `2/7/20` <dbl>,
#   `2/8/20` <dbl>, `2/9/20` <dbl>, `2/10/20` <dbl>, …
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names
```

US_cases %>% pivot_longer(cols = -(UID:Combined_Key), names_to = "date", values_to = "cases")


```
\section(table)
# A tibble: 3,692,910 × 13
        UID iso2  iso3  code3  FIPS Admin2 Provi…¹ Count…²   Lat Long_
      <dbl> <chr> <chr> <dbl> <dbl> <chr>  <chr>   <chr>   <dbl> <dbl>
 1 84001001 US    USA     840  1001 Autau… Alabama US       32.5 -86.6
 2 84001001 US    USA     840  1001 Autau… Alabama US       32.5 -86.6
 3 84001001 US    USA     840  1001 Autau… Alabama US       32.5 -86.6
 4 84001001 US    USA     840  1001 Autau… Alabama US       32.5 -86.6
 5 84001001 US    USA     840  1001 Autau… Alabama US       32.5 -86.6
 6 84001001 US    USA     840  1001 Autau… Alabama US       32.5 -86.6
 7 84001001 US    USA     840  1001 Autau… Alabama US       32.5 -86.6
 8 84001001 US    USA     840  1001 Autau… Alabama US       32.5 -86.6
 9 84001001 US    USA     840  1001 Autau… Alabama US       32.5 -86.6
10 84001001 US    USA     840  1001 Autau… Alabama US       32.5 -86.6
# … with 3,692,900 more rows, 3 more variables: Combined_Key <chr>,
#   date <chr>, cases <dbl>, and abbreviated variable names
#   ¹​Province_State, ²​Country_Region
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names
```

US_cases <- US_cases %>% pivot_longer(cols= -(UID:Combined_Key), names_to = "date", values_to = "cases") %>% select(Admin2:cases) %>% mutate(date=mdy(date)) %>% select(-c(Lat, Long_))


US_cases



```
\section(table)
# A tibble: 3,692,910 × 6
   Admin2  Province_State Country_Region Combined_Key date       cases
   <chr>   <chr>          <chr>          <chr>        <date>     <dbl>
 1 Autauga Alabama        US             Autauga, Al… 2020-01-22     0
 2 Autauga Alabama        US             Autauga, Al… 2020-01-23     0
 3 Autauga Alabama        US             Autauga, Al… 2020-01-24     0
 4 Autauga Alabama        US             Autauga, Al… 2020-01-25     0
 5 Autauga Alabama        US             Autauga, Al… 2020-01-26     0
 6 Autauga Alabama        US             Autauga, Al… 2020-01-27     0
 7 Autauga Alabama        US             Autauga, Al… 2020-01-28     0
 8 Autauga Alabama        US             Autauga, Al… 2020-01-29     0
 9 Autauga Alabama        US             Autauga, Al… 2020-01-30     0
10 Autauga Alabama        US             Autauga, Al… 2020-01-31     0
# … with 3,692,900 more rows
# ℹ Use `print(n = ...)` to see more rows
```

##### Same of above to be done with US deaths: 


US_deaths <- US_deaths %>% pivot_longer(cols = -(UID:Population), names_to = "date", values_to = "deaths") %>% select(Admin2:deaths) %>% mutate(date = mdy(date)) %>% select(-c(Lat, Long_))


US_deaths



```
\section(table)
# A tibble: 3,692,910 × 7
   Admin2  Province_State Country_…¹ Combi…² Popul…³ date       deaths
   <chr>   <chr>          <chr>      <chr>     <dbl> <date>      <dbl>
 1 Autauga Alabama        US         Autaug…   55869 2020-01-22      0
 2 Autauga Alabama        US         Autaug…   55869 2020-01-23      0
 3 Autauga Alabama        US         Autaug…   55869 2020-01-24      0
 4 Autauga Alabama        US         Autaug…   55869 2020-01-25      0
 5 Autauga Alabama        US         Autaug…   55869 2020-01-26      0
 6 Autauga Alabama        US         Autaug…   55869 2020-01-27      0
 7 Autauga Alabama        US         Autaug…   55869 2020-01-28      0
 8 Autauga Alabama        US         Autaug…   55869 2020-01-29      0
 9 Autauga Alabama        US         Autaug…   55869 2020-01-30      0
10 Autauga Alabama        US         Autaug…   55869 2020-01-31      0
# … with 3,692,900 more rows, and abbreviated variable names
#   ¹​Country_Region, ²​Combined_Key, ³​Population
# ℹ Use `print(n = ...)` to see more rows
```


US <- US_cases %>% full_join(US_deaths)



```
\section(table)
Joining, by = c("Admin2", "Province_State", "Country_Region",
"Combined_Key", "date")
```


US
```
\section(table)
# A tibble: 3,692,910 × 8
   Admin2  Province_…¹ Count…² Combi…³ date       cases Popul…⁴ deaths
   <chr>   <chr>       <chr>   <chr>   <date>     <dbl>   <dbl>  <dbl>
 1 Autauga Alabama     US      Autaug… 2020-01-22     0   55869      0
 2 Autauga Alabama     US      Autaug… 2020-01-23     0   55869      0
 3 Autauga Alabama     US      Autaug… 2020-01-24     0   55869      0
 4 Autauga Alabama     US      Autaug… 2020-01-25     0   55869      0
 5 Autauga Alabama     US      Autaug… 2020-01-26     0   55869      0
 6 Autauga Alabama     US      Autaug… 2020-01-27     0   55869      0
 7 Autauga Alabama     US      Autaug… 2020-01-28     0   55869      0
 8 Autauga Alabama     US      Autaug… 2020-01-29     0   55869      0
 9 Autauga Alabama     US      Autaug… 2020-01-30     0   55869      0
10 Autauga Alabama     US      Autaug… 2020-01-31     0   55869      0
# … with 3,692,900 more rows, and abbreviated variable names
#   ¹​Province_State, ²​Country_Region, ³​Combined_Key, ⁴​Population
# ℹ Use `print(n = ...)` to see more rows
```



global <- global %>% unite("Combined_Key", c(Province_State, Country_Region), sep = ", ", na.rm=TRUE, remove=FALSE)



global
```
\section(table)
# A tibble: 295,921 × 6
   Combined_Key Province_State Country_Region date       cases deaths
   <chr>        <chr>          <chr>          <date>     <dbl>  <dbl>
 1 Afghanistan  NA             Afghanistan    2020-02-24     5      0
 2 Afghanistan  NA             Afghanistan    2020-02-25     5      0
 3 Afghanistan  NA             Afghanistan    2020-02-26     5      0
 4 Afghanistan  NA             Afghanistan    2020-02-27     5      0
 5 Afghanistan  NA             Afghanistan    2020-02-28     5      0
 6 Afghanistan  NA             Afghanistan    2020-02-29     5      0
 7 Afghanistan  NA             Afghanistan    2020-03-01     5      0
 8 Afghanistan  NA             Afghanistan    2020-03-02     5      0
 9 Afghanistan  NA             Afghanistan    2020-03-03     5      0
10 Afghanistan  NA             Afghanistan    2020-03-04     5      0
# … with 295,911 more rows
# ℹ Use `print(n = ...)` to see more rows
```




# Step 3: Visualizaing & Analyzing, the question is: "Add at least two different visualizations & some analysis to your Rmd.  Does this raise additional questions that you should investigate?  "


US_by_State <- US %>% group_by(Province_State, Country_Region, date) %>% summarize(cases = sum(cases), deaths = sum(deaths), Population = sum(Population)) %>% mutate(deaths_per_mill = deaths*1000000 / Population) %>% ungroup()



```
\section(table)
`summarise()` has grouped output by
'Province_State', 'Country_Region'.
You can override using the `.groups`
argument.
```


US_by_State
```
\section(table)
# A tibble: 64,090 × 7
   Provinc…¹ Count…² date       cases
   <chr>     <chr>   <date>     <dbl>
 1 Alabama   US      2020-01-22     0
 2 Alabama   US      2020-01-23     0
 3 Alabama   US      2020-01-24     0
 4 Alabama   US      2020-01-25     0
 5 Alabama   US      2020-01-26     0
 6 Alabama   US      2020-01-27     0
 7 Alabama   US      2020-01-28     0
 8 Alabama   US      2020-01-29     0
 9 Alabama   US      2020-01-30     0
10 Alabama   US      2020-01-31     0
# … with 64,080 more rows, 3 more
#   variables: deaths <dbl>,
#   Population <dbl>,
#   deaths_per_mill <dbl>, and
#   abbreviated variable names
#   ¹​Province_State, ²​Country_Region
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable name
```






US_totals <- US_by_State %>% group_by(Country_Region, date) %>% summarize(cases = sum(cases), deaths = sum(deaths), Population = sum(Population)) %>% select(Country_Region, date, cases, deaths, Population) %>% ungroup()



```
\section(table)

`summarise()` has grouped output by
'Country_Region'. You can override using the
`.groups` argument.
```




US_totals %>% filter(cases > 0) %>% ggplot(aes(x = date, y = cases)) + geom_line(aes(color = "cases")) + geom_point(aes(color = "cases")) + geom_line(aes(y = deaths, color = "deaths")) + scale_y_log10() + theme(legend.position="bottom", axis.text.x = element_text(angle = 90)) + labs(title="COVID19 IN US", y=NULL)




state <- "New York"




US_by_State %>% filter(Province_State ==state) %>% filter(cases > 0) %>% ggplot(aes(x = date, y = cases)) + geom_line(aes(color = "cases")) + geom_point(aes(color = "cases")) + geom_line(aes(y = deaths, color = "deaths")) + scale_y_log10() + theme(legend.position="bottom", axis.text.x = element_text(angle = 90)) + labs(title="COVID19 IN New York", y=NULL)






max(US_totals$date)



```
\section(table)
[1] "2023-01-30"
```

max(US_totals$deaths)
```
\section(table)
[1] 1107855
```




## Analyzing the Data: 


US_by_State <- US_by_State %>% mutate(new_cases = cases - lag(cases), new_deaths = deaths - lag(deaths))




US_totals <- US_totals %>% mutate(new_cases = cases - lag(cases), new_deaths = deaths - lag(deaths))




tail(US_totals)



```
\section(table)

# A tibble: 6 × 7
  Country_…¹ date        cases deaths
  <chr>      <date>      <dbl>  <dbl>
1 US         2023-01-26 1.02e8 1.11e6
2 US         2023-01-27 1.02e8 1.11e6
3 US         2023-01-28 1.02e8 1.11e6
4 US         2023-01-29 1.02e8 1.11e6
5 US         2023-01-30 1.02e8 1.11e6
6 US         2023-01-31 1.02e8 1.11e6
# … with 3 more variables:
#   Population <dbl>,
#   new_cases <dbl>,
#   new_deaths <dbl>, and
#   abbreviated variable name
#   ¹​Country_Region
# ℹ Use `colnames()` to see all variable names
```



tail(US_totals %>% select(new_cases, new_deaths, everything()))


```
\select(table)

# A tibble: 6 × 7
  new_ca…¹ new_d…² Count…³ date      
     <dbl>   <dbl> <chr>   <date>    
1    62454     845 US      2023-01-26
2    17178      92 US      2023-01-27
3     3849      11 US      2023-01-28
4     2607       0 US      2023-01-29
5    27077     210 US      2023-01-30
6    35040     627 US      2023-01-31
# … with 3 more variables:
#   cases <dbl>, deaths <dbl>,
#   Population <dbl>, and
#   abbreviated variable names
#   ¹​new_cases, ²​new_deaths,
#   ³​Country_Region
# ℹ Use `colnames()` to see all variable names
```




US_totals %>% ggplot(aes(x = date, y = new_cases)) + geom_line(aes(color = "new_cases")) + geom_point(aes(color = "new_cases")) + geom_line(aes(y = new_deaths, color = "new_deaths")) + geom_point(aes(y = new_deaths, color = "new_deaths")) + scale_y_log10() + theme(legend.position="bottom", axis.text.x = element_text(angle = 90)) + labs(title = "COVID19 in US", y=NULL)


```
\section(table)
Warning messages:
1: Transformation introduced infinite
values in continuous y-axis 
2: Transformation introduced infinite
values in continuous y-axis 
3: In self$trans$transform(x) : NaNs produced
4: Transformation introduced infinite
values in continuous y-axis 
5: In self$trans$transform(x) : NaNs produced
6: Transformation introduced infinite
values in continuous y-axis 
7: Removed 1 row containing missing
values (`geom_line()`). 
8: Removed 1 rows containing missing
values (`geom_point()`). 
9: Removed 1 row containing missing
values (`geom_line()`). 
10: Removed 2 rows containing missing
values (`geom_point()`).
```



US_State_totals <- US_by_State %>% group_by(Province_State) %>% summarize(deaths = max(deaths), cases = max(cases), population = max(Population), cases_per_thou = 1000* cases / population, deaths_per_thou = 1000* deaths / population) %>% filter(cases > 0, population > 0)



US_State_totals %>% slice_min(deaths_per_thou, n = 10) 




```
\section(table)

# A tibble: 10 × 6
   Provin…¹ deaths  cases popul…² cases…³ death…⁴
   <chr>     <dbl>  <dbl>   <dbl>   <dbl>   <dbl>
 1 America…     34 8.32e3   55641    150.   0.611
 2 Norther…     41 1.35e4   55144    245.   0.744
 3 Virgin …    129 2.45e4  107268    229.   1.20 
 4 Hawaii     1786 3.77e5 1415872    266.   1.26 
 5 Vermont     889 1.50e5  623989    241.   1.42 
 6 Puerto …   5693 1.08e6 3754939    289.   1.52 
 7 Utah       5253 1.08e6 3205958    337.   1.64 
 8 Alaska     1473 3.04e5  740995    411.   1.99 
 9 Distric…   1422 1.76e5  705749    249.   2.01 
10 Washing…  15381 1.90e6 7614893    250.   2.02 
# … with abbreviated variable names
#   ¹​Province_State, ²​population,
#   ³​cases_per_thou, ⁴​deaths_per_thou
```



US_State_totals %>% slice_min(deaths_per_thou, n = 10) %>% select(deaths_per_thou, cases_per_thou, everything())




```
\section(table)
# A tibble: 10 × 6
   deaths…¹ cases…² Provi…³ deaths  cases popul…⁴
      <dbl>   <dbl> <chr>    <dbl>  <dbl>   <dbl>
 1    0.611    150. Americ…     34 8.32e3   55641
 2    0.744    245. Northe…     41 1.35e4   55144
 3    1.20     229. Virgin…    129 2.45e4  107268
 4    1.26     266. Hawaii    1786 3.77e5 1415872
 5    1.42     241. Vermont    889 1.50e5  623989
 6    1.52     289. Puerto…   5693 1.08e6 3754939
 7    1.64     337. Utah      5253 1.08e6 3205958
 8    1.99     411. Alaska    1473 3.04e5  740995
 9    2.01     249. Distri…   1422 1.76e5  705749
10    2.02     250. Washin…  15381 1.90e6 7614893
# … with abbreviated variable names
#   ¹​deaths_per_thou, ²​cases_per_thou,
#   ³​Province_State, ⁴​population
```


US_State_totals %>% slice_max(deaths_per_thou, n = 10) %>% select(deaths_per_thou, cases_per_thou, everything())



```
\section(table)

# A tibble: 10 × 6
   deaths…¹ cases…² Provi…³ deaths  cases popul…⁴
      <dbl>   <dbl> <chr>    <dbl>  <dbl>   <dbl>
 1     4.50    329. Arizona  32775 2.40e6 7278717
 2     4.46    321. Oklaho…  17652 1.27e6 3956971
 3     4.44    329. Missis…  13225 9.78e5 2976149
 4     4.38    354. West V…   7849 6.35e5 1792147
 5     4.27    317. New Me…   8953 6.65e5 2096829
 6     4.26    330. Arkans…  12852 9.97e5 3017804
 7     4.26    328. Alabama  20870 1.61e6 4903185
 8     4.23    361. Tennes…  28883 2.47e6 6829174
 9     4.17    303. Michig…  41690 3.03e6 9986857
10     4.03    338. New Je…  35794 3.00e6 8882190
# … with abbreviated variable names
#   ¹​deaths_per_thou, ²​cases_per_thou,
#   ³​Province_State, ⁴​population
```


## Modeling the Data: 


mod <- lm(deaths_per_thou ~ cases_per_thou, data=US_State_totals)

summary(mod)


```
\section(table)

Call:
lm(formula = deaths_per_thou ~ cases_per_thou, data = US_State_totals)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.3012 -0.5974  0.1333  0.6455  1.1848 

Coefficients:
                Estimate Std. Error t value
(Intercept)    -0.350169   0.722865  -0.484
cases_per_thou  0.011294   0.002346   4.815
               Pr(>|t|)    
(Intercept)        0.63    
cases_per_thou 1.23e-05 ***
---
Signif. codes:  
0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.8567 on 54 degrees of freedom
Multiple R-squared:  0.3004,	Adjusted R-squared:  0.2874 
F-statistic: 23.18 on 1 and 54 DF,  p-value: 1.23e-05
```




US_State_totals %>% slice_min(cases_per_thou)


```
\section(table)
# A tibble: 1 × 6
  Province…¹ deaths cases popul…² cases…³ death…⁴
  <chr>       <dbl> <dbl>   <dbl>   <dbl>   <dbl>
1 American …     34  8320   55641    150.   0.611
# … with abbreviated variable names
#   ¹​Province_State, ²​population,
#   ³​cases_per_thou, ⁴​deaths_per_thou
```




US_State_totals %>% slice_max(cases_per_thou)




```
\section(table)

# A tibble: 1 × 6
  Provinc…¹ deaths  cases popul…² cases…³ death…⁴
  <chr>      <dbl>  <dbl>   <dbl>   <dbl>   <dbl>
1 Rhode Is…   3821 454211 1059361    429.    3.61
# … with abbreviated variable names
#   ¹​Province_State, ²​population,
#   ³​cases_per_thou, ⁴​deaths_per_thou
```



x_grid <- seq(1, 151)
new_df <- tibble(cases_per_thou = x_grid)
US_State_totals %>% mutate(pred = predict(mod))


```
\section(table)

# A tibble: 56 × 7
   Provin…¹ deaths  cases popul…² cases…³ death…⁴
   <chr>     <dbl>  <dbl>   <dbl>   <dbl>   <dbl>
 1 Alabama   20870 1.61e6  4.90e6    328.   4.26 
 2 Alaska     1473 3.04e5  7.41e5    411.   1.99 
 3 America…     34 8.32e3  5.56e4    150.   0.611
 4 Arizona   32775 2.40e6  7.28e6    329.   4.50 
 5 Arkansas  12852 9.97e5  3.02e6    330.   4.26 
 6 Califor… 100078 1.20e7  3.95e7    303.   2.53 
 7 Colorado  14034 1.75e6  5.76e6    304.   2.44 
 8 Connect…  11964 9.67e5  3.57e6    271.   3.36 
 9 Delaware   3254 3.26e5  9.74e5    335.   3.34 
10 Distric…   1422 1.76e5  7.06e5    249.   2.01 
# … with 46 more rows, 1 more variable:
#   pred <dbl>, and abbreviated variable names
#   ¹​Province_State, ²​population,
#   ³​cases_per_thou, ⁴​deaths_per_thou
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names
```



US_tot_w_pred <- US_State_totals %>% mutate(pred = predict(mod))
US_tot_w_pred



```
\section(table)

# A tibble: 56 × 7
   Provin…¹ deaths  cases popul…² cases…³ death…⁴
   <chr>     <dbl>  <dbl>   <dbl>   <dbl>   <dbl>
 1 Alabama   20870 1.61e6  4.90e6    328.   4.26 
 2 Alaska     1473 3.04e5  7.41e5    411.   1.99 
 3 America…     34 8.32e3  5.56e4    150.   0.611
 4 Arizona   32775 2.40e6  7.28e6    329.   4.50 
 5 Arkansas  12852 9.97e5  3.02e6    330.   4.26 
 6 Califor… 100078 1.20e7  3.95e7    303.   2.53 
 7 Colorado  14034 1.75e6  5.76e6    304.   2.44 
 8 Connect…  11964 9.67e5  3.57e6    271.   3.36 
 9 Delaware   3254 3.26e5  9.74e5    335.   3.34 
10 Distric…   1422 1.76e5  7.06e5    249.   2.01 
# … with 46 more rows, 1 more variable:
#   pred <dbl>, and abbreviated variable names
#   ¹​Province_State, ²​population,
#   ³​cases_per_thou, ⁴​deaths_per_thou
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names
```






US_tot_w_pred %>% ggplot() + geom_point(aes(x = cases_per_thou, y = deaths_per_thou), color = "blue") + geom_point(aes(x = cases_per_thou, y = pred), color = "red")




# Step 4 : Bias Indentification, the question is: "Write the conclusion to your project report and include any possible sources of bias.  Be sure to identify what your personal bias might be and how you have mitigated that."


### Conclusion: the main processes of a Data Science project is -1- Importing the data set and explaining from where I get the data    -2- Tidy and Transforming the data in a manner that help making the anlysis easer such that we sort the data based on our interest of searching, we modify the structre of the data frame by adding our custom columns add rows and/or by delting some columns and rows that are not needed in out interest       -3 Visualizaing the Results, such that we creat the visualization of our modified data such that we can ask ourseleves questions that could not appear by only reading data without visulaization, ending up with final conclusion of the data frame aided by obtained visualization, in addition we are able to apply models to the data frame obtained by that visulaiztion.      -4-We need to identify the bias sources and how to counter them by either apply to the data science team some new stratigies such as regrouping a temporary team for a specific project, or by applying learend stratigies from similar previous projects in the same field.

###Bias:    In my opnion I did not manipulate of the data in terms of the race because I belive it is a source f biace, but also, I belive we can counter this bias by working on the data with a team with a various races so we assure no bias could happen.

## End of Steps given in the lecture 



## Additional Steps Adding by ME : 



US_totals %>% ggplot(aes(x = date, y = new_cases)) + geom_line(aes(color = "new_cases")) + geom_point(aes(color = "new_cases")) + geom_line(aes(y = new_deaths, color = "new_deaths")) + geom_point(aes(y = new_deaths, color = "new_deaths")) + scale_y_log10() + theme(legend.position="bottom", axis.text.x = element_text(angle = 90)) + labs(title = "COVID19 in global", y=NULL)


```
\section(table)
Warning messages:
1: Transformation introduced infinite
values in continuous y-axis 
2: Transformation introduced infinite
values in continuous y-axis 
3: In self$trans$transform(x) : NaNs produced
4: Transformation introduced infinite
values in continuous y-axis 
5: In self$trans$transform(x) : NaNs produced
6: Transformation introduced infinite
values in continuous y-axis 
7: Removed 1 row containing missing
values (`geom_line()`). 
8: Removed 1 rows containing missing
values (`geom_point()`). 
9: Removed 1 row containing missing
values (`geom_line()`). 
10: Removed 2 rows containing missing
values (`geom_point()`).
```



US_State_totals <- US_by_State %>% group_by(Province_State) %>% summarize(deaths = max(deaths), cases = max(cases), population = max(Population), cases_per_thou = 100* cases / population, deaths_per_thou = 100* deaths / population) %>% filter(cases > 0, population > 0)



US_State_totals %>% slice_min(deaths_per_thou, n = 10) 




```
\section(table)

# A tibble: 10 × 6
   Provin…¹ deaths  cases popul…² cases…³ death…⁴
   <chr>     <dbl>  <dbl>   <dbl>   <dbl>   <dbl>
 1 America…     34 8.32e3   55641    150.   0.611
 2 Norther…     41 1.35e4   55144    245.   0.744
 3 Virgin …    129 2.45e4  107268    229.   1.20 
 4 Hawaii     1786 3.77e5 1415872    266.   1.26 
 5 Vermont     889 1.50e5  623989    241.   1.42 
 6 Puerto …   5693 1.08e6 3754939    289.   1.52 
 7 Utah       5253 1.08e6 3205958    337.   1.64 
 8 Alaska     1473 3.04e5  740995    411.   1.99 
 9 Distric…   1422 1.76e5  705749    249.   2.01 
10 Washing…  15381 1.90e6 7614893    250.   2.02 
# … with abbreviated variable names
#   ¹​Province_State, ²​population,
#   ³​cases_per_thou, ⁴​deaths_per_thou
```



US_State_totals %>% slice_min(deaths_per_thou, n = 10) %>% select(deaths_per_thou, cases_per_thou, everything())




```
\section(table)
# A tibble: 10 × 6
   deaths…¹ cases…² Provi…³ deaths  cases popul…⁴
      <dbl>   <dbl> <chr>    <dbl>  <dbl>   <dbl>
 1    0.611    150. Americ…     34 8.32e3   55641
 2    0.744    245. Northe…     41 1.35e4   55144
 3    1.20     229. Virgin…    129 2.45e4  107268
 4    1.26     266. Hawaii    1786 3.77e5 1415872
 5    1.42     241. Vermont    889 1.50e5  623989
 6    1.52     289. Puerto…   5693 1.08e6 3754939
 7    1.64     337. Utah      5253 1.08e6 3205958
 8    1.99     411. Alaska    1473 3.04e5  740995
 9    2.01     249. Distri…   1422 1.76e5  705749
10    2.02     250. Washin…  15381 1.90e6 7614893
# … with abbreviated variable names
#   ¹​deaths_per_thou, ²​cases_per_thou,
#   ³​Province_State, ⁴​population
```


US_State_totals %>% slice_max(deaths_per_thou, n = 10) %>% select(deaths_per_thou, cases_per_thou, everything())



```
\section(table)

# A tibble: 10 × 6
   deaths…¹ cases…² Provi…³ deaths  cases popul…⁴
      <dbl>   <dbl> <chr>    <dbl>  <dbl>   <dbl>
 1     4.50    329. Arizona  32775 2.40e6 7278717
 2     4.46    321. Oklaho…  17652 1.27e6 3956971
 3     4.44    329. Missis…  13225 9.78e5 2976149
 4     4.38    354. West V…   7849 6.35e5 1792147
 5     4.27    317. New Me…   8953 6.65e5 2096829
 6     4.26    330. Arkans…  12852 9.97e5 3017804
 7     4.26    328. Alabama  20870 1.61e6 4903185
 8     4.23    361. Tennes…  28883 2.47e6 6829174
 9     4.17    303. Michig…  41690 3.03e6 9986857
10     4.03    338. New Je…  35794 3.00e6 8882190
# … with abbreviated variable names
#   ¹​deaths_per_thou, ²​cases_per_thou,
#   ³​Province_State, ⁴​population
```


## Modeling the Data: 


mod <- lm(deaths_per_thou ~ cases_per_thou, data=US_State_totals)

summary(mod)


```
\section(table)

Call:
lm(formula = deaths_per_thou ~ cases_per_thou, data = US_State_totals)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.3012 -0.5974  0.1333  0.6455  1.1848 

Coefficients:
                Estimate Std. Error t value
(Intercept)    -0.350169   0.722865  -0.484
cases_per_thou  0.011294   0.002346   4.815
               Pr(>|t|)    
(Intercept)        0.63    
cases_per_thou 1.23e-05 ***
---
Signif. codes:  
0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.8567 on 54 degrees of freedom
Multiple R-squared:  0.3004,	Adjusted R-squared:  0.2874 
F-statistic: 23.18 on 1 and 54 DF,  p-value: 1.23e-05
```




US_State_totals %>% slice_min(cases_per_thou)


```
\section(table)
# A tibble: 1 × 6
  Province…¹ deaths cases popul…² cases…³ death…⁴
  <chr>       <dbl> <dbl>   <dbl>   <dbl>   <dbl>
1 American …     34  8320   55641    150.   0.611
# … with abbreviated variable names
#   ¹​Province_State, ²​population,
#   ³​cases_per_thou, ⁴​deaths_per_thou
```




US_State_totals %>% slice_max(cases_per_thou)




```
\section(table)

# A tibble: 1 × 6
  Provinc…¹ deaths  cases popul…² cases…³ death…⁴
  <chr>      <dbl>  <dbl>   <dbl>   <dbl>   <dbl>
1 Rhode Is…   3821 454211 1059361    429.    3.61
# … with abbreviated variable names
#   ¹​Province_State, ²​population,
#   ³​cases_per_thou, ⁴​deaths_per_thou
```



x_grid <- seq(1, 151)
new_df <- tibble(cases_per_thou = x_grid)
US_State_totals %>% mutate(pred = predict(mod))


```
\section(table)

# A tibble: 56 × 7
   Provin…¹ deaths  cases popul…² cases…³ death…⁴
   <chr>     <dbl>  <dbl>   <dbl>   <dbl>   <dbl>
 1 Alabama   20870 1.61e6  4.90e6    328.   4.26 
 2 Alaska     1473 3.04e5  7.41e5    411.   1.99 
 3 America…     34 8.32e3  5.56e4    150.   0.611
 4 Arizona   32775 2.40e6  7.28e6    329.   4.50 
 5 Arkansas  12852 9.97e5  3.02e6    330.   4.26 
 6 Califor… 100078 1.20e7  3.95e7    303.   2.53 
 7 Colorado  14034 1.75e6  5.76e6    304.   2.44 
 8 Connect…  11964 9.67e5  3.57e6    271.   3.36 
 9 Delaware   3254 3.26e5  9.74e5    335.   3.34 
10 Distric…   1422 1.76e5  7.06e5    249.   2.01 
# … with 46 more rows, 1 more variable:
#   pred <dbl>, and abbreviated variable names
#   ¹​Province_State, ²​population,
#   ³​cases_per_thou, ⁴​deaths_per_thou
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names
```



US_tot_w_pred <- US_State_totals %>% mutate(pred = predict(mod))
US_tot_w_pred



```
\section(table)

# A tibble: 56 × 7
   Provin…¹ deaths  cases popul…² cases…³ death…⁴
   <chr>     <dbl>  <dbl>   <dbl>   <dbl>   <dbl>
 1 Alabama   20870 1.61e6  4.90e6    328.   4.26 
 2 Alaska     1473 3.04e5  7.41e5    411.   1.99 
 3 America…     34 8.32e3  5.56e4    150.   0.611
 4 Arizona   32775 2.40e6  7.28e6    329.   4.50 
 5 Arkansas  12852 9.97e5  3.02e6    330.   4.26 
 6 Califor… 100078 1.20e7  3.95e7    303.   2.53 
 7 Colorado  14034 1.75e6  5.76e6    304.   2.44 
 8 Connect…  11964 9.67e5  3.57e6    271.   3.36 
 9 Delaware   3254 3.26e5  9.74e5    335.   3.34 
10 Distric…   1422 1.76e5  7.06e5    249.   2.01 
# … with 46 more rows, 1 more variable:
#   pred <dbl>, and abbreviated variable names
#   ¹​Province_State, ²​population,
#   ³​cases_per_thou, ⁴​deaths_per_thou
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names
```






US_tot_w_pred %>% ggplot() + geom_point(aes(x = cases_per_thou, y = deaths_per_thou), color = "blue") + geom_point(aes(x = cases_per_thou, y = pred), color = "orange")



